name: Build CrossDesk Server

on:
  push:
    branches: ["**"]
    tags: ["*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          IMAGE_NAME=crossdesk-server
          IMAGE_TAG=${GITHUB_REF_NAME:-latest}
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f docker/Dockerfile .

      - name: Save built binary as artifact
        run: |
          docker create --name temp crossdesk-server:${GITHUB_REF_NAME:-latest}
          docker cp temp:/crossdesk-server/crossdesk_server ./crossdesk_server
          docker rm temp
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: crossdesk_server
          path: crossdesk_server

      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_TAG=${GITHUB_REF_NAME}
          DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME=${DOCKER_USER}/crossdesk-server

          echo "Pushing ${IMAGE_NAME}:${IMAGE_TAG} and ${IMAGE_NAME}:latest"

          docker tag crossdesk-server:${IMAGE_TAG} ${IMAGE_NAME}:${IMAGE_TAG}
          docker tag crossdesk-server:${IMAGE_TAG} ${IMAGE_NAME}:latest

          docker push ${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${IMAGE_NAME}:latest

      - name: Publish GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: crossdesk_server
          generate_release_notes: true
